stages:
- name: build
  steps:
  - runScriptConfig:
      image: maven:3.6-jdk-8-alpine
      shellScript: mvn install -Dmaven.test.skip=true
  when:
    event: {}
- name: 部署
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile
      buildContext: .
      tag: sbfx/myeureka:v1.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.0.106:445
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: 部署应用
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
    env:
      CICD_GIT_TAG: v1.${CICD_EXECUTION_SEQUENCE}
  - applyYamlConfig:
      path: ./servicedep.yml
timeout: 60
branch:
  include:
  - master
notification: {}
